#nome da pipeline
name: Run Basic Testes

# em que momento será executada
on:
  #nesse caso vai rodar toda vez que fizer um pull request (toda vez que subir uma branch)
  pull_request:
    branches: [master]

# para rodar em uma hora agendada
# nesse caso vai rodar as (Às 20:00​​ todos os dias da semana, de segunda a sexta-feira.)
# esse site ajuda a montar o agendamento (https://crontab.guru/)
# on:
#   schedule:
#     - cron: '0 20 * * 1-5'

jobs:
  # oque vai ser feito na pipeline
  # nesse momento só teremos um job: rodas os testes
  cypress-run:
    # maquina que será executado
    runs-on: ubuntu-latest

    #passo a passo para rodar os testes
    steps:
      #clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

        #execução e config do projeto
      - name: Run testes
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
